<?php

class SBWModelFormatter {

  protected $model;


  public function SBWModelFormatter($model) {
    if ( !isset($model) ) {
      trigger_error("No model specified", E_USER_ERROR);
    }
    $this->model = $model;
  }


  public function formatModel() {
    $wikitext = '';
    $wikitext .= <<<WIKI
{{Physicochemical_model
|name=
|organism=
|cell type=
|cell processes=
|modeler=
|references=
}}
== Description ==



<!-- the following text was auto-generated by the model importer -->
== Model Contents ==

'''Species:'''
<ask limit="15">
[[Category:Model species]]
[[Part of model::{{PAGENAME}}]]
[[Full name::*]]
[[Synonyms::*]]
[[Uniprot accession number::*]]
[[Has molecular function::*]]
[[Localizes to cellular component::*]]
</ask>

'''Reactions:'''
<ask limit="15">
[[Category:Model interactions]]
[[Part of model::{{PAGENAME}}]]
[[name::*]]
[[mass action rule::*]]
[[parameters::*]]
</ask>

WIKI;

    // TODO: output has_species and has_reaction

    return $wikitext;
  }


  public function formatSpecies($id) {
    $wikitext = '';

    $species = $this->model->getSpecies($id);
    $name          = $species->name;
    $initial_value = $species->initialConcentration;
    $wikitext .= <<<WIKI
{{Physicochemical_species
|name=$name
|synonyms=
|full_name=
|uniprot=
|molecule_type=
|localization=
|initial_value=$initial_value
|references=
}}
== Description == 



<!-- the following text was auto-generated by the model importer -->
== Reactions ==

WIKI;

    return $wikitext;
  }


  public function formatReaction($id) {
    $wikitext = '';

    $reaction = $this->model->getReaction($id);
    $name          = $reaction->name;
    $mass_action   = $reaction->asText();
    $wikitext .= <<<WIKI
{{Physicochemical_reaction
|name=$name
|mass_action=$mass_action
|parameters=
|references=
}}

== Description == 



<!-- the following text was auto-generated by the model importer -->
     
WIKI;

    return $wikitext;
  }


  public function formatAll() {
    $wikitext = '';

    $wikitext .= "<div style='border: 1px dashed #000000; background: #fcf8ff; padding: .5em;'>\n";
    $wikitext .= $this->formatModel();
    $wikitext .= "</div>\n----\n";
    
    foreach ( $this->model->getSpeciesIds() as $id ) {
      $name = $this->model->getSpecies($id)->name;
      $wikitext .= "<div style='border: 1px dashed #000000; background: #f8fff8; padding: .5em;'>\n";
      $wikitext .= $this->formatSpecies($id);
      $wikitext .= "</div>\n----\n";
    }

    foreach ( $this->model->getReactionIds() as $id ) {
      $name = $this->model->getReaction($id)->name;
      $wikitext .= "<div style='border: 1px dashed #000000; background: #fff8f8; padding: .5em;'>\n";
      $wikitext .= $this->formatReaction($id);
      $wikitext .= "</div>\n----\n";
    }

    return $wikitext;
  }

}

?>